### ISSUE TITLE
GCloud image with GPU support

### ISSUE THREAD

**Issue by arshak** [studioml/studio#102]
Should we make an image that has all this pre-configured.

It takes 5 minutes to do all this which we can avoid.

gcloud beta compute instance-templates create studio-template \
    --machine-type n1-standard-8 \
    --boot-disk-size 250GB \
    --accelerator type=nvidia-tesla-k80,count=1 \
    --image-family ubuntu-1604-lts --image-project ubuntu-os-cloud \
    --maintenance-policy TERMINATE --restart-on-failure \
    --scopes "https://www.googleapis.com/auth/source.read_only","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring.write","https://www.googleapis.com/auth/trace.append","https://www.googleapis.com/auth/devstorage.read_only" \
    --metadata startup-script='#!/bin/bash
    echo "Checking for CUDA and installing."
    # Check for CUDA and try to install.
    if ! dpkg-query -W cuda; then
      curl -O http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
      dpkg -i ./cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
      # need to host the cudnn somewhere publicly accessible
      curl -O curl -O cudnn-8.0-linux-x64-v5.1.tgz
      tar xvf cudnn-8.0-linux-x64-v5.1.tgz
      cp cuda/lib64/* /usr/local/cuda/lib64/
      cp cuda/include/cudnn.h /usr/local/cuda/include/
      ldconfig /usr/local/cuda/lib64
    fi 
    apt-get update
    apt-get install cuda -y
    apt-get install -y python3-pip python3-dev
    pip3 install --upgrade pip3 h5py pillow
    pip3 install --upgrade numpy tensorflow-gpu
    git clone https://github.com/studioml/studio.git /opt/studio
    cd /opt/studio && pip3 install -e .
    studio start remote worker --queue=projects/X/topics/studio    
    '

**Comment by pzhokhov** [comment]
PR out: https://github.com/studioml/studio/pull/214
