### ISSUE TITLE
Cannot uninstall studio after installing it from git project directory

### ISSUE THREAD

**Issue by jasonzliang** [studioml/studio#103]
After I install studio using the following command:
`git clone https://github.com/studioml/studio && cd studio && pip install -e .
`there seems to be no way to uninstall the pip package other than manually deleting the files in /usr/loca/...

**Comment by ilblackdragon** [comment]
That seems like pip issue: https://stackoverflow.com/questions/17346619/how-to-uninstall-editable-packages-with-pip-installed-with-e 
I'm not sure we can fix it here.

**Comment by pzhokhov** [comment]
Since PR for CD of packages is out https://github.com/studioml/studio/pull/213 (and there is a bit of discussion about versioning therein), from now on users can (should?) mainly use pypi package. I'll close this; if someone feels strongly about us fixing it - let's talk.
