### ISSUE TITLE
Pass Startup Shell Script to Remote Workers

### ISSUE THREAD

**Issue by jasonzliang** [studioml/studio#129]
It would be nice if we could specify a startup script as an argument to 'studio run', the idea is that when a remote worker starts up, it would execute this startup script.
One use case might be to install some necessary dependencies before running the actual python script.

**Comment by karlmutch** [comment]
I dont know much about how pip interacts with the virtualenv, could you do that from within your python application ?

**Comment by jasonzliang** [comment]
You dont want to do it from within the python script because it might involve a one time change such as installing dependencies. 
You dont want to reinstall the dependencies everytime you run a script.

**Comment by jasonzliang** [comment]
A fix for this issue is proposed in pull request #144

**Comment by pzhokhov** [comment]
Due to possibility of running on a server / in a datacenter, proper solution for this issue is to use singularity and virtualization. I'll close this for now - we have a hack / deprecated startup_script option, and will wait for the era of singularity promised by @karlmutch
