### ISSUE TITLE
Google project details should be read from the credentials file using the credential storage APIs

### ISSUE THREAD

**Issue by karlmutch** [studioml/studio#140]
As an experimenter 
I want to use the project ID from the google credentials files, GOOGLE_APPLICATION_CREDENTIALS
In order that projects can be used without needing the yaml cfg file changing

**Comment by pzhokhov** [comment]
Fixed here: https://github.com/studioml/studio/commit/01a5c3c80e489479de536e99dcf06b7b71ccab3a
