### ISSUE TITLE
Fix qualified URL issues with new API versions

### ISSUE THREAD

**Issue by karlmutch** [studioml/studio#142]
qualified artifact locations contain more than one scheme after changes to endpoint logic within runner.py

Fix issue with missing README.rst files inside the pip installer

Quotes might be broken inside ec2 worker but no way of testing

**Comment by pzhokhov** [comment]
@karlmutch , is this still an issue?

**Comment by karlmutch** [comment]
I believe we are OK with this issue now so closing.
