### ISSUE TITLE
Keras not in requirements.txt

### ISSUE THREAD

**Issue by jasonzliang** [studioml/studio#158]
I notice that some of the unit tests run scripts which require Keras, however keras is not part of the requirements for StudioML

**Comment by ilblackdragon** [comment]
Would be great to actually not require for studio itself. For tests we can have a separate requirements.txt file - as we will want to have other framework examples/tests too [like pytorch], and installation [and especially runtime] of studio shouldn't depend on it

**Comment by jasonzliang** [comment]
Added to test_requirements.txt in master
