### ISSUE TITLE
Change tensorflow to tensorflow-gpu in requirements.txt

### ISSUE THREAD

**Issue by jasonzliang** [studioml/studio#159]
Currently, if you already have tensorflow-gpu installed, after you install studioml, it will install and start using the cpu version of tensorflow instead. However if you then uninstall tensorflow (cpu version) it will complain the following when you launch studio:

```
studio-ui
Traceback (most recent call last):
  File "/usr/local/bin/studio-ui", line 4, in <module>
    __import__('pkg_resources').require('studioml==0.0.0')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 972, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tensorflow' distribution was not found and is required by studioml
```

If we make tensorflow-gpu a requirement instead, this  would not happen and it will automatically fall back to cpu mode if no gpu is detected.

**Comment by nieoh** [comment]
@karlmutch I remember you were talking about having to deal with tensorflow vs tensorflow-gpu

**Comment by karlmutch** [comment]
Yes I manually deploy it before the go custom runner starts so it is always there.  I do it to save time really when spinning up the virtualenv. 

The only complication for the python runner would be that it might be hard to predict exactly which hardware accelerators are being used and, with many new ones in the wings, pip names could become unpredictable.

The python runner might need to have custom logic to load the packages rather than relying on the requirements.txt which is created before the experiment is targeted at specific hardware.

**Comment by jasonzliang** [comment]
@pzhokhov @arshak What do you guys think about this?

**Comment by pzhokhov** [comment]
I am not convinced about the falling back to cpu mode. I have just tried it on my laptop (mac with no nvidia gpu), and when I try to import tensorflow, I get this:

> >>> import tensorflow as tf
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/peter.zhokhov/studioml1/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import *
>   File "/Users/peter.zhokhov/studioml1/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 51, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/Users/peter.zhokhov/studioml1/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "/Users/peter.zhokhov/studioml1/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "/Users/peter.zhokhov/studioml1/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "/Users/peter.zhokhov/studioml1/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> ImportError: dlopen(/Users/peter.zhokhov/studioml1/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
>   Referenced from: /Users/peter.zhokhov/studioml1/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
>   Reason: image not found
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/install_sources#common_installation_problems
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.

**Comment by karlmutch** [comment]
A recent issue https://github.com/studioml/studio/pull/237 modified studio to specify the correct tensorflow variant based upon the resources specified by the user.  The reference hard coded inside requirements.txt is no longer present.

If after testing @jasonzliang it does not meet expectations add an issue to handle the new case.

Thanks
