### ISSUE TITLE
Python3: errors on import

### ISSUE THREAD

**Issue by DSLituiev** [studioml/studio#164]
I have freshly installed studioml and trying to run:

```studio-run --cloud=ec2 train_densenet.py
Traceback (most recent call last):
  File "/usr/local/bin/studio-run", line 2, in <module>
    from studio import runner
  File "/usr/local/lib/python3.4/dist-packages/studio/runner.py", line 13, in <module>
    from local_queue import LocalQueue
ImportError: No module named 'local_queue'
```

Changing the above line to `from .local_queue import LocalQueue` fixes this error, but there are tons of similar errors to follow. I guess it was written for python2.7?

**Comment by ilblackdragon** [comment]
Yeah, it's been working written for python2.7. If you have time - please feel free to send a PR with fixes for Python3.

**Comment by DSLituiev** [comment]
I was able to fix most python2 oddities, but now I see that it executes the supplied script with Python2, though the `studio` package runs on python3. Where do you specify the kernel?

**Comment by DSLituiev** [comment]
found. replacing with
```
import sys
sys.executable```

**Comment by nieoh** [comment]
@DSLituiev Aside from the Python2 oddities (basestring, iteritems, etc), I think the import error is related to this: https://stackoverflow.com/questions/25276329/cant-load-python-modules-installed-via-pip-from-site-packages-directory (it seems that sometimes with Python3, you have set the Python path for the site-packages again/correctly. I know I've definitely run into similar issues). The import error, changing it to `from .local_queue import LocalQueue` doesn't seem like strictly a Python version issue to me.

**Comment by pietromarchesi** [comment]
I have also tried both the standard pip install from pypi and the pip install from cloned repo, just wanted to mention the errors I came across. In the first case, other than the `ImportError` mentioned above, I also get this one:
```
Traceback (most recent call last):
  File "/home/pietro/Envs/basic3/bin/studio-ui", line 2, in <module>
    from studio import studio
  File "/home/pietro/Envs/basic3/lib/python3.5/site-packages/studio/studio.py", line 4, in <module>
    import model
ImportError: No module named 'model'
``` 

Furthermore, when installing from pypi, I cannot seem to find the `default_config.yaml` file. When installing from the cloned repo, both `studio ui` and `studio run` give 

```
  File "/home/pietro/Envs/mynewstudio/bin/studio-run", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/pietro/pythonprojects/studio/studio/scripts/studio-run", line 2, in <module>
    from studio import runner
  File "/home/pietro/pythonprojects/studio/studio/__init__.py", line 2, in <module>
    import fs_tracker
ImportError: No module named 'fs_tracker'
```

**Comment by karlmutch** [comment]
@pietromarchesi The second item you mention seems to point at an import error for fs_tracker.  Is the default_config.yaml file completely missing, or do you have more logging that points at the missing yaml file?

Thanks for your report BTW.

**Comment by pietromarchesi** [comment]
Yes, indeed, although I haven't had time to go through the source code and figure out why there are all these import errors. Regarding the `default_config.yaml`, I was looking for it because in the 'getting started' section of the tutorials it says to go in there and uncomment some lines, and it's not in the package folder.

**Comment by nieoh** [comment]
@pietromarchesi For the first error (and other Import errors mentioned above), have you tried the solution from [`here?`](https://stackoverflow.com/questions/25276329/cant-load-python-modules-installed-via-pip-from-site-packages-directory) Along the lines of `export PYTHONPATH=$PYTHONPATH:/home/pietro/Envs/basic3/lib/python3.5/site-packages`

**Comment by pzhokhov** [comment]
In this PR https://github.com/studioml/studio/pull/215 the studio.ml code should become python2 and 3 compatible (and be tested against both). We are still missing auto-selection of python for cloud workers, but I'll create a separate issue for that and close this one for now.
