### ISSUE TITLE
Anaconda support

### ISSUE THREAD

**Issue by nieoh** [studioml/studio#173]
From issue #149.

**Comment by pzhokhov** [comment]
As of now, compatible with anaconda for local runs and cloud runs that don't require anaconda-specific packages (i.e. cloud runs will always be executed in python). Anaconda in the cloud can be hacked in a pretty straightforward way (by adding anaconda installation commands into the cloud startup script); however, the cleaner solution will be to support containers in the cloud (via docker or singularity).
