### ISSUE TITLE
Jupyter notebooks support

### ISSUE THREAD

**Issue by pzhokhov** [studioml/studio#174]

**Comment by ilblackdragon** [comment]
How about a cell level magic that works as `studio run` alternative?
```
%%studio.run

code ...
```
Also would be useful to output link to experiment info on hosted website.

And with flags, something like this:
```
%%studio.run(cloud='gcloud', workers=2, ...)
```

The issue here, is that capturing state of the environment if wanting to run remote.
It's possible to do via `globals()/locals()`, but not sure if it's a good idea.

**Comment by deus42** [comment]
I like the idea of a cell-level magic. Any hints how to implement it?

**Comment by pzhokhov** [comment]
I think we can start with the case which required explicitly passing all variables and only works with pickleable parameters. The general idea would be this - if in the cell the function call looks like:
`x = f(a,b,c)` we'll create a wrapper script that pickles the arguments a,b,c (maybe f as well - need to look into how python serialization works with functions) and passes them as artifacts; on the worker side, it will get artifacts, unpickle data and call f; then pickle the return value and pass it back as an artifact. Then later we can add globals/locals as variables. 
Fortunately, turns out that we already have most of this pickle-arguments - call - pickle return values logic implemented  in @jasonzliang's completion service (the name is still open to debate, but functionality is essentially exactly as described); so we can build on that. 

My PM @arshak permitting, I'd like to start work on that soon.

**Comment by pzhokhov** [comment]
Now I realize that last time I commented on this I knew nothing of cell magics or jupyter notebooks in general. @ilblackdragon's idea is actually super cool, and it works beautifully too. @deus42, I tried to take a first stab at it. Here is the PR: https://github.com/studioml/studio/pull/236. It still a bit inconvenient in the sense that it does not print any output on the way - that's something I am going to add next

**Comment by pzhokhov** [comment]
At a further consideration, streaming of the logs may be not that great of an idea (besides being pretty painful) - because it will create duplicate entries when running locally. Instead, we'll put up a link to zoo.studio.ml (or whatever api server is specified in the config)

**Comment by pzhokhov** [comment]
Anyways, the PR is out: https://github.com/studioml/studio/pull/236, and I'll close this issue
