### ISSUE TITLE
FileNotFoundError for aws keys

### ISSUE THREAD

**Issue by DSLituiev** [studioml/studio#182]
Trying to  `studio run --cloud=ec2 train_mnist_keras.py`, getting:

```
INFO:EC2WorkerManager:Reading AWS prices from cache...
INFO:EC2WorkerManager:Done!
Traceback (most recent call last):
  File "/usr/local/bin/studio-run", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/data/dlituiev/studio/studio/scripts/studio-run", line 3, in <module>
    runner.main()
  File "/data/dlituiev/studio/studio/runner.py", line 295, in main
    resources_needed)
  File "/data/dlituiev/studio/studio/runner.py", line 360, in submit_experiments
    timeout=runner_args.cloud_timeout)
  File "/data/dlituiev/studio/studio/ec2cloud_worker.py", line 110, in start_worker
    resources_needed, queue_name, timeout=timeout)
  File "/data/dlituiev/studio/studio/ec2cloud_worker.py", line 172, in _get_startup_script
    with open(self.auth_cookie, 'r') as f
FileNotFoundError: [Errno 2] No such file or directory: '~/.studioml/keys/[keyid]'
```

**Comment by pzhokhov** [comment]
Fundamentally, that happens because the authentication key (for firebase, not for aws) is not generated. A simple workaround is to run ``studio ui``, go to localhost:5000 in the browser - that will generate the authentication key and place it in the right spot. I agree, however, that the stacktrace is very cryptic; I'll add a fail-fast clear message for it.

**Comment by pzhokhov** [comment]
Although I am trying to run it now off master branch without the key and I am getting rather the expected "Authentication required! Either specify use_email_auth in config file, or run studio and go to webui (localhost:5000 by default) to authenticate using google credentials" message. 
Could you please check if the issue has not been accidentally fixed, and if it has not, provide more info (specifically, are the contents of your ~/.studioml/config.yaml file). Thanks!
