### ISSUE TITLE
Mlkube and k8

### ISSUE THREAD

**Issue by bhack** [studioml/studio#186]
Could be interesting to collaborate with [Mlkube](https://github.com/jlewi/mlkube.io) /cc @jlewi

**Comment by jlewi** [comment]
I would certainly be interested in learning more about studioml. I tried out studioml a couple days ago but didn't get very far. I ran into auth issues trying to setup firebase.

I was particularly interested in the UI/dashboard functionality of studioml because that's one of the key pieces I think is missing form an ML/TF on K8s story.

**Comment by bhack** [comment]
The project now it is an official TF repository https://github.com/tensorflow/k8s

**Comment by aronchick** [comment]
We'd love to work together! We've launched a new repo https://github.com/google/kubeflow - any chance you've heard of it?

**Comment by karlmutch** [comment]
Hi,  Yes have heard of it and have taken a look.

Currently studio focuses on providing a platform neutral tool for ENN and ML.  The design targets a master and distributed worker approach with storage and queuing as the two dependencies that have any coupling into our experiments.  

Within Sentient we do use k8s along with our own compute infrastructure, and layer studioml on top of this.  In the past our focus was to integrate the cloud offerings into the studioml code base, these implementations still exist and are used today.  Having said that, we have begun using Minio for S3 and RabbitMQ for queuing to create a reference deployment in preference to having cloud provider dependencies.  This has worked very well for us.  In these case k8s is used as the platform and we leverage kops, kubeadm et al to provide the infrastructure.  The main emphasis here is that generic k8s is being used.

The above is a Sentient perspective which could easily be changed, and is a narrow one given several others are using studioml and might be seeking different directions for their deployments and use of studioml.

If you would like to connect please feel free to drop me a line via karl.mutch (at) sentient.ai

**Comment by karlmutch** [comment]
Update : microk8s has been used with StudioML and the http://github.com/leaf-ai/studio-go-runner project.  There is a yaml file for microk8s style installations that leverage RabbitMQ and Minio to create an entirely self contained studioml eco-system.  studio go runner is a Go based stand-in for the traditional python worker designed for a combination of commercial purposes and also for use within our Evolutionary Algorithm research team.  I don't know if it will be of use but it is there in any event.

I also have a new email karl.mutch@cognizant.com or karlmutch@gmail.com.
