### ISSUE TITLE
Question: Could all results be loaded to a pandas dataframe?

### ISSUE THREAD

**Issue by yuvval** [studioml/studio#195]
Hi 

I recently discovered this project and it looks really good.
I was wondering if there is a programmatic way of loading the results, instead of just viewing them in the web UI. I.e. Is the results database is viewable? Is it possible to load it into pandas?
What about the artifacts, are they accessible from outside the training script?

Thanks

**Comment by pzhokhov** [comment]
Hi @yuvval ! 
Yes, you can totally do that. Something along the lines of:

`
from studio import model
with model.get_db_provider() as db:
    experiment = db.get_experiment(<experiment_key>)
`
will return an experiment object that contains all the info about the experiment with key <experiment_key>
