### ISSUE TITLE
GPU Memory Requirements

### ISSUE THREAD

**Issue by jasonzliang** [studioml/studio#210]
Right now the assumption is hard coded in get_available_gpus() from gpu_util.py that 90% of the total gpu memory is avaliable. This leads to problems when running locally where other processes may use gpu memory. We should change this to a explicit requirement for certain amount of GPU memory.

**Comment by karlmutch** [comment]
When using the python runner on cloud instances the configuration of memory and GPUs is fixed and the cloud instance type is under the control of the studioml yaml configuration file.  In these cases access to the GPU resources are exclusively yours.  Which leaves us with the case where you are running the studioml python runner on your own private hardware, such as your laptop etc.

In these cases the amount of memory consumed by other applications is not fixed and the runner would not be able to make assumptions about when external processes might start, or stop.  Which means that the only way to have partitioning of memory is either by processes interacting with each other to co-ordinate memory consumption, or to have the GPU driver do this for you and this is not a supported cuda feature.

I sent a private DM about doing this in a cooperative manner between applications.  In the meantime lets close this for now and reopen when we can maybe describe a future feature or strategy to address this type of requirement.  We can reopen the issue if you would like re-surface the discussion again.
