### ISSUE TITLE
Completion Service Does not Work with http database

### ISSUE THREAD

**Issue by jasonzliang** [studioml/studio#228]
If we use the following in .studioml/config.yaml under database:

```
type: http
serverUrl: https://studio-ed756.appspot.com
```

the completion service does not work. Otherwise it works with 
`type: FireBase`

**Comment by pzhokhov** [comment]
Should be working with the cloud executors now. The internal go runner still requires a specific storage that is not google cloud storage (but rather s3), but that should be also fixed shortly via deploying internal apiserver with S3-backed storage.
