### ISSUE TITLE
allow multiple completion service instances to use same queue/worker pool to submit but receive results back separately

### ISSUE THREAD

**Issue by jasonzliang** [studioml/studio#239]
this would be useful for evaluating individuals in multiple different EAs since evaluation time can vary a lot and having 1 worker pool per EA might lead to a little of idle time

**Comment by pzhokhov** [comment]
This should work more or less out of the box the following way - create one instance of completion service with queue=<queue_name> and cloud = <ec2, gcloud, ...> , and the other one - with queue=<queue_name> and cloud=None. The spin-up of instances will be handled by the first instances, and both will submit experiments to the same queue. I'll close this for now, let me if it does not work, and then we can take it from there.
