### ISSUE TITLE
Allow specifying ssh_key for new instances

### ISSUE THREAD

**Issue by yaroslavvb** [studioml/studio#248]
It defaults to "None" using following command

`studio run --verbose=debug --queue=studio --cloud=ec2 --force-git train_mnist_keras.py
`

**Comment by pzhokhov** [comment]
That is a desired behaviour (to my opinion), for 2 reasons - 1) when things work, user should not need to go ssh-ing into instances :) and 2) when the key is specified, that generates an extra security group, and there is no mechanism to clean those up; and eventually AWS caps those. So I wanted it to be somewhat of a conscious effort to add a ssh keypair to the worker. 
But what we can also do is make it configurable from config file.
