### ISSUE TITLE
KMeans demo does not run on Jupyter Notebook. NameError: name 'get_ipython' is not defined

### ISSUE THREAD

**Issue by htansetiawan** [studioml/studio#311]
Tutorial was copied from https://www.sentient.ai/blog/zero-overhead-scalable-machine-learning/

![image](https://user-images.githubusercontent.com/16394050/36811173-bd54fb9c-1c81-11e8-8a2e-e910219c136a.png)

![image](https://user-images.githubusercontent.com/16394050/36811311-2795d850-1c82-11e8-8ddd-fdced46a55dd.png)

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import urllib
import gzip, pickle, numpy
from studio import magics, fs_tracker
%matplotlib inline

%%time
%%studio_run

import pickle, gzip, numpy, urllib, json

urllib.urlretrieve("http://deeplearning.net/data/mnist/mnist.pkl.gz", "mnist.pkl.gz")
with gzip.open("mnist.pkl.gz", "rb") as f:
    train_set, valid_set, test_set = pickle.load(f)
    
kmeans = KMeans(n_clusters=10, verbose=1)
fit_result = kmeans.fit(train_set[0], train_set[1])
train_set = None
test_set = None

Running studio with experiment key 1519848792_jupyter_1e94df3b-6719-45f2-9f08-811b783d9476
Experiment progress can be viewed/shared at:
http://zoo.studio.ml/experiment/1519848792_jupyter_1e94df3b-6719-45f2-9f08-811b783d9476
['--capture=/Users/henrytan/.studioml/experiments/1519848792_jupyter_1e94df3b-6719-45f2-9f08-811b783d9476/_ns:_ns', '--capture-once=.:workspace', '--force-git', '--experiment=1519848792_jupyter_1e94df3b-6719-45f2-9f08-811b783d9476', '_script.py']
studio run: submitted experiment 1519848792_jupyter_1e94df3b-6719-45f2-9f08-811b783d9476
Traceback (most recent call last):

  File "_script.py", line 9, in <module>

    _M.__dict__.update(pickle.load(f))

  File "/Users/henrytan/anaconda2/envs/ipykernel_py2/lib/python2.7/pickle.py", line 1384, in load

    return Unpickler(file).load()

  File "/Users/henrytan/anaconda2/envs/ipykernel_py2/lib/python2.7/pickle.py", line 864, in load

    dispatch[key](self)

  File "/Users/henrytan/anaconda2/envs/ipykernel_py2/lib/python2.7/pickle.py", line 1139, in load_reduce

    value = func(*args)

  File "/Users/henrytan/anaconda2/envs/ipykernel_py2/lib/python2.7/site-packages/dill/dill.py", line 797, in _import_module

    return getattr(__import__(module, None, None, [obj]), obj)

  File "/Users/henrytan/anaconda2/envs/ipykernel_py2/lib/python2.7/site-packages/studio/magics.py", line 113, in <module>

    ip = get_ipython()

NameError: name 'get_ipython' is not defined

An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

**Comment by pzhokhov** [comment]
Hi @htansetiawan ! Really sorry about the big lag. Looks like the issue you are facing is due to slight differences between the anaconda and pip packages. Unfortunately, at the moment I don't have a good solution for you other than try it with pip (the easiest way to do that would be via a virtualenv, I'll be happy to provide more detailed instructions / help if you choose to try it out). We are working on the full anaconda support, but it's not there yet.

**Comment by karlmutch** [comment]
Closing issue as it is now idle...
