### ISSUE TITLE
Getting error in azure notebooks while deploying : ImportError: No module named azure.storage.blob

### ISSUE THREAD

**Issue by adarsha04** [studioml/studio#312]
We are usign azure ml stodio workspace and trying to deploy model using azure notebooks present in ml studio.

Imported azure-storage using below code.
!pip install azure-storage==0.36.0

Its working when i run locally but when its deployed to ML studio workspace, its giving us this error:

{u'error': {u'message': u'Module execution encountered an error.', u'code': u'ModuleExecutionError', u'details': [{u'message': u'Error 0085: The following error occurred during script evaluation, please view the output log for more information:\r\n---------- Start of error message from Python interpreter ----------\r\nCaught exception while executing function: Traceback (most recent call last):\n File "\server\InvokePy.py", line 120, in executeScript\n outframe = mod.azureml_main(*inframes)\n File "\temp\1450604638.py", line 1094, in azureml_main\n results.append(__user_function(client_code))\n File "", line 17, in final_model\n File "", line 5, in data_input\nImportError: **No module named azure.storage.blob**\n\r\n\r\n---------- End of error message from Python interpreter ----------', u'code': u'85', u'target': u'Execute Python Script RRS'}]}}

Code used to deploy:

from azureml import Workspace
ws = Workspace()
workspace_id = 'xxxxx'
authorization_token = 'yyyyyy'

from azureml import services
@services.publish(workspace_id, authorization_token)
@services.types(client_code = int)
@services.returns(int)

def final_model(client_code): 
    import pandas as pd
    data_input(account_name,key)  # this function has code related to importing data from blob
    return client_code    
    
service_url = final_model.service.url 
api_key = final_model.service.api_key
help_url = final_model.service.help_url
service_id = final_model.service.service_id

What is the package name which is present in ML studio workspace to import data from blob so that it runs when its deployed there.

**Comment by pzhokhov** [comment]
Hi @adarsha04! Sorry about the big lag. I think you are referring to Azure ML studio (https://studio.azureml.net/) which is a Microsoft product, not open-source and has little to do with our project (studio.ml) save for similarity in names. I'd recommend submitting the question to the Azure support via azure portal (portal.azure.com)
