### ISSUE TITLE
Studio Ml future roadmap

### ISSUE THREAD

**Issue by arita37** [studioml/studio#389]
Hello,

I found studio ML well designed and the right fit for ML production setup.
Am just worried about Studio ML future and future roadmap.

Also, the doc was not updated for a while....

**Comment by karlmutch** [comment]
Hi there,

StudioML was originally conceived for use cases that had a public facing component, the model zoo, and several other hosting style features that for now are not the primary motivation of those active on the project.

Currently most of the activity related to the project is driven by the Evolutionary AI team within Cognizant, and Cognizant commercial delivery of AI based offerings.  Our current plans for the project are to continue using it for our cattle vs pets style of model wrangling. The use cases that StudioML addresses are a much larger superset of what we are actively working on as a single maintainer.  We do however maintain the code base, for example dropping Python2 support, and fixing CVE related dependencies are recent activities. So as one maintainer our aim for the base python implementation is one of stability. With this focus we are running thousands of StudioML tasks every day in-house, and this is growing significantly in both research and commercial contexts.

StudioML may seem very quiet despite saying this, the reason for this is that we have layered a significant amount of software on top of the core python implementation, which at its heart is a python task dispatcher with some AI eco-system awareness.  For example we have the research team using an experiment orchestration layer on top of the core python Studio libraries, proprietary.  We also have an open source go implementation of the python runner that is maintained separately and has a focus on running on Kubernetes clusters stretching from public infrastructure down to walled gardens air gapped from the internet, https://github.com/leaf-ai/studio-go-runner.

I hope this gives some transparency as to what we, Cognizant, are doing and helps with your decision.

Please feel free to re-open this ticket if you would like additional information.

Thanks for your interest,
Karl

**Comment by arita37** [comment]
Thanks.

Was looking for simple and straightforward
framework, with conda integration.
It seems the core API is stabilized and maintained

(Vs MLFlow which is in dev. Mode).

Thanks
