### ISSUE TITLE
CI Solution Testing

### ISSUE THREAD

**Issue by karlmutch** [studioml/studio#90]
As a user of TFStudio
I want to have CI testing of production deployments prior to releases
In order that the various deployment scenarios are assured of working

Terraform based testing inside Google, Amazon and Private infrastructure

**Comment by pzhokhov** [comment]
Given that we don't have integration with terraform yet, I don't know how this would look like with it; but the way the test suite is set up now - if the google application credentials are present, the tests that use gcloud workers are run; if the aws credentials are present - tests that use ec2 are run. An example of this would be https://travis-ci.org/SentientTechnologies/studio/ (for now the tests there are still failing miserably, but I am working on that). As for private compute - it may make more sense to have tests on the go runner side, I think. I'll close this issue; but we may need to come back to this once (and if) we get to integrate with terraform
