### ISSUE TITLE
CI coarse grained standalone testing

### ISSUE THREAD

**Issue by karlmutch** [studioml/studio#91]
As a developer or product owner of TFStudio
I want to have Development Environment, and CI standalone testing of functional portions of TFStudio
In order that regression and new functionality can be tested during development, or travis builds

docker swarm based testing using volume mounts and local file based queue

**Comment by pzhokhov** [comment]
@karlmutch does this PR cover it? https://github.com/studioml/studio/pull/169

**Comment by pzhokhov** [comment]
@karlmutch I'll close this for now given that we have travis CI
