### ISSUE TITLE
Experiments waiting in the queue need a maximum lifetime

### ISSUE THREAD

**Issue by karlmutch** [studioml/studio#95]
As an experimenter
I want to be able to specify how long I am willing to wait experiment to run on a runner before I abandon waiting
In order that money is not wasted on experiments that I am no longer interest in

They still sit in the queue but as soon as they arrive on a runner it simply dumps them without running the experiment

**Comment by pzhokhov** [comment]
Implemented here: https://github.com/studioml/studio/pull/269
The gist of the change is this - there is a field "experimentLifetime" in the config that tells how long should experiment exist (if time.time()  > experiment.time_added + experimentLifetime, then experiment is stale)
